name: CI dev

on:
  push:
    branches: [dev, serenity]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          # registry: ghcr.io
          # username: ${{ github.actor }}
          # password: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Set environment variable
      #   run: |
      #     SHORT_SHA_COMMIT=$(git rev-parse --short HEAD)
      #     echo CONTAINER_RELEASE_IMAGE=ghcr.io/harisato/aura-safe:${GITHUB_REF_NAME}_${SHORT_SHA_COMMIT} >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=registry,ref=quochai194/aura-safe:buildcache
          cache-to: type=registry,ref=quochai194/aura-safe:buildcache,mode=max
          push: true
          tags: quochai194/aura-safe:latest
  # update-manifest:
  #   needs: build-and-push
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set environment variable
  #       run: |
  #         SHORT_SHA_COMMIT=$(git rev-parse --short HEAD)
  #         echo CONTAINER_RELEASE_IMAGE=ghcr.io/aura-nw/safe-react:${GITHUB_REF_NAME}_${SHORT_SHA_COMMIT} >> $GITHUB_ENV
  #         echo REPO_MANIFEST_NAME=gitops >> $GITHUB_ENV
  #         echo REPO_MANIFEST_URL=github.com/aura-nw/gitops.git >> $GITHUB_ENV
  #         echo REPO_MANIFEST_BRANCH=master >> $GITHUB_ENV
  #         echo REPO_MANIFEST_ENV_DEV=./clusters/k8s-dev/multisig-safe >> $GITHUB_ENV
  #         echo REPO_MANIFEST_ENV_STAGING=./clusters/k8s-prod/multisig-safe >> $GITHUB_ENV
  #         echo REPO_MANIFEST_ENV_MAIN=./clusters/k8s-main/multisig-safe >> $GITHUB_ENV
  #         echo REPO_MANIFEST_TAG_IMAGE=image_multisig_safe_frontend >> $GITHUB_ENV
  #         echo REPO_MANIFEST_ENV_EUPHORIA=./clusters/k8s-testnet-euphoria/multisig-safe >> $GITHUB_ENV
  #         echo REPO_MANIFEST_ENV_SERENITY=./clusters/k8s-testnet-serenity/multisig-safe >> $GITHUB_ENV
  #         echo REPO_MANIFEST_ENV_HALO=./clusters/k8s-testnet-halo/multisig-safe >> $GITHUB_ENV
  #     - name: Update manifest
  #       env:
  #         PERSONAL_ACCESS_TOKEN: ${{ secrets.REGISTRY_PASSWORD }}
  #       run: |
  #         chmod 777 -R ./ci
  #         ./ci/updateManifest.sh
